# Generated by Django 4.1.7 on 2023-06-18 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField()),
                (
                    "mounth",
                    models.CharField(
                        choices=[
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mayi"),
                            (6, "Juin"),
                            (7, "Julliet"),
                            (8, "Août"),
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Decembre"),
                        ],
                        max_length=255,
                    ),
                ),
                ("payment_statut", models.BooleanField()),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="ReservationModel",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("reservation_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rerservation",
                "verbose_name_plural": "Rerservations",
            },
        ),
        migrations.CreateModel(
            name="RoomModel",
            fields=[
                (
                    "room_number",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("capacite", models.IntegerField()),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "student_number",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("telephone", models.CharField(max_length=255)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residenceApp.paymentmodel",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residenceApp.reservationmodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AddField(
            model_name="reservationmodel",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="residenceApp.roommodel"
            ),
        ),
        migrations.CreateModel(
            name="ComplaintModel",
            fields=[
                ("complaint_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residenceApp.studentmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
            },
        ),
    ]
