# Generated by Django 4.1.7 on 2023-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residenceApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="department",
            field=models.CharField(
                choices=[(1, "GIT"), (2, "GEM"), (3, "GC"), (4, "Aero"), (5, "GI")],
                default="null",
                max_length=50,
            ),
        ),
    ]
