# Generated by Django 4.1.7 on 2023-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residenceApp", "0003_alter_studentmodel_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="department",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
