# Generated by Django 4.1.7 on 2023-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residenceApp", "0004_alter_studentmodel_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommodel",
            name="remaining_space",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
