# Generated by Django 4.1.7 on 2023-06-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residenceApp", "0009_remove_studentmodel_payment_paymentmodel_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmodel",
            name="student",
        ),
    ]
