# Generated by Django 4.1.7 on 2023-06-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("residenceApp", "0010_remove_paymentmodel_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="student",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                to="residenceApp.studentmodel",
            ),
        ),
    ]
